services:
  backend:
    build: ./backend
    container_name: 'backend'
    ports:
      - 3000:3000
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgres://dev:password@postgres_db:5432/pfe_db"
      JWT_SECRET: "secret"
      HASH_ROUNDS: 10
  frontend:
    build: ./frontend
    container_name: 'frontend'
    ports:
      - 4200:4200
  postgres_db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgressql/data
      - ./initdb:/docker-entrypoint-initdb.d
      - ./backend/migrations:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pfe_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  postgres-data: