INSERT INTO pfe.questions (question_type, category, sub_category, question)
VALUES
-- 1. ENERGIE & CARBONE
('ESG', '1. ENERGIE & CARBONE', '1.1. GESTION DE L''ENERGIE', 'Suivez-vous la consommation d''énergie de XXX ?'),
('ESG', '1. ENERGIE & CARBONE', '1.1. GESTION DE L''ENERGIE', 'Si vous la suivez, veuillez indiquer votre consommation d''énergie totale des 12 derniers mois (en kWh)'),
('ESG', '1. ENERGIE & CARBONE', '1.1. GESTION DE L''ENERGIE', 'Avez-vous un contrat vert avec votre fournisseur d''énergie ?'),
('ESG', '1. ENERGIE & CARBONE', '1.1. GESTION DE L''ENERGIE', 'Produisez-vous de l''électricité sur site (par exemple, avec des panneaux solaires) ?'),
('ESG', '1. ENERGIE & CARBONE', '1.1. GESTION DE L''ENERGIE', 'Qu''avez-vous mis en place pour limiter votre consommation d''énergie ? Veuillez sélectionner toutes les réponses applicables.'),
('ESG', '1. ENERGIE & CARBONE', '1.1. GESTION DE L''ENERGIE', 'Avez-vous mis en place des initiatives pour sensibiliser vos travailleur·euses sur les bonnes pratiques en matière de consommation d''énergie ?'),
('ESG', '1. ENERGIE & CARBONE', '1.2. EMPREINTE CARBONE', 'Avez-vous calculé l''empreinte carbone des activités de XXX ?'),
('ESG', '1. ENERGIE & CARBONE', '1.2. EMPREINTE CARBONE', 'Si vous la calculez, veuillez indiquer votre empreinte carbone de Scope 1 (en tonnes de CO2 équivalent) :'),
('ESG', '1. ENERGIE & CARBONE', '1.2. EMPREINTE CARBONE', 'Si vous la calculez, veuillez indiquer votre empreinte carbone de Scope 2 (en tonnes de CO2 équivalent) :'),
('ESG', '1. ENERGIE & CARBONE', '1.2. EMPREINTE CARBONE', 'Si vous la calculez, veuillez indiquer votre empreinte carbone de Scope 3 (en tonnes de CO2 équivalent) :'),
('ESG', '1. ENERGIE & CARBONE', '1.2. EMPREINTE CARBONE', 'Si vous avez réalisé un rapport d''empreinte carbone pour XXX, que comprend-il ? Veuillez sélectionner toutes les réponses applicables.'),
('ESG', '1. ENERGIE & CARBONE', '1.2. EMPREINTE CARBONE', 'Quelle(s) pratique(s) avez-vous mise(s) en place pour limiter votre empreinte carbone ?'),
('ESG', '1. ENERGIE & CARBONE', '1.2. EMPREINTE CARBONE', 'Proposez-vous des ateliers de sensibilisation et des formations sur les émissions de gaz à effet de serre à destination de vos travailleur·euses ? (par exemple, la fresque du climat)'),
('ESG', '1. ENERGIE & CARBONE', '1.2. EMPREINTE CARBONE', 'Quel pourcentage de vos fournisseurs (en valeur monétaire) se trouvent à moins de 80 km de vos installations ?'),
('ESG', '1. ENERGIE & CARBONE', '1.2. EMPREINTE CARBONE', 'Quel pourcentage de votre transport amont et aval (approvisionnement et livraison) est effectué à l''aide de modes de transport à faibles émissions de carbone (par exemple, vélo-cargo, train, voilier, etc.) ?'),
('ESG', '1. ENERGIE & CARBONE', '1.2. EMPREINTE CARBONE', 'Avez-vous optimisé votre chaîne de valeur afin de réduire les distances de transport, par exemple en rapprochant vos fournisseurs, en centralisant vos sites de production ou en réorganisant vos réseaux de distribution ?'),
('ESG', '1. ENERGIE & CARBONE', '1.2. EMPREINTE CARBONE', 'Quelle(s) mesure(s) avez-vous prise(s) avec vos fournisseurs pour limiter les émissions carbones liées à votre chaine d''approvisionnement ?'),

-- 2. EAU, MATIERES PREMIERES ET FOURNITURES
('ESG', '2. EAU, MATIERES PREMIERES ET FOURNITURES', '2.1. EAU', 'Mesurez-vous la consommation d''eau de XXX ?'),
('ESG', '2. EAU, MATIERES PREMIERES ET FOURNITURES', '2.1. EAU', 'Si vous la mesurez, veuillez indiquer votre consommation d''eau (en litres) :'),
('ESG', '2. EAU, MATIERES PREMIERES ET FOURNITURES', '2.1. EAU', 'Qu''avez-vous mis en place pour limiter votre consommation d''eau ? Veuillez sélectionner toutes les réponses applicables.'),
('ESG', '2. EAU, MATIERES PREMIERES ET FOURNITURES', '2.1. EAU', 'Avez-vous mis en place des initiatives pour sensibiliser vos travailleur·euses à la gestion de l''eau et à sa consommation ?'),
('ESG', '2. EAU, MATIERES PREMIERES ET FOURNITURES', '2.1. EAU', 'XXX a-t-elle pris l''une ou plusieurs de ces mesures concernant la consommation d''eau dans sa chaine d''approvisionnement ?'),
('ESG', '2. EAU, MATIERES PREMIERES ET FOURNITURES', '2.2. MATIERES PREMIERES ET FOURNITURES', 'XXX a-t-elle pris l''une ou plusieurs de ces mesures concernant l''utilisation des ressources ?'),
('ESG', '2. EAU, MATIERES PREMIERES ET FOURNITURES', '2.2. MATIERES PREMIERES ET FOURNITURES', 'Avez-vous mis en place des initiatives pour sensibiliser vos travailleur·euses à l''utilisation des ressources ?'),
('ESG', '2. EAU, MATIERES PREMIERES ET FOURNITURES', '2.2. MATIERES PREMIERES ET FOURNITURES', 'Quel pourcentage de vos matériaux (en volume) provient de matériaux recyclés, de composants réutilisés et/ou de matériaux certifiés d''origine durable ?'),

-- 3. DÉCHETS
('ESG', '3. DÉCHETS', '3.1. DÉCHETS', 'Suivez-vous les quantités et les types de déchets produits par XXX ?'),
('ESG', '3. DÉCHETS', '3.1. DÉCHETS', 'Si vous la suivez, veuillez indiquer la quantité totale de déchets produits par votre organisation au cours des 12 derniers mois (en tonnes) ?'),
('ESG', '3. DÉCHETS', '3.1. DÉCHETS', 'Si vous la suivez, veuillez indiquer la quantité de déchets dangereux produits par votre organisation au cours des 12 derniers mois (en tonnes) ?
(exemples de déchets dangereux : équipements électroniques, piles, cartouches d''encre, déchets industriels, batteries, peintures, etc.)'),
('ESG', '3. DÉCHETS', '3.1. DÉCHETS', 'Quelle(s) pratique(s) avez-vous mise(s) en place pour réduire la production de déchets et optimiser leur gestion ?'),
('ESG', '3. DÉCHETS', '3.1. DÉCHETS', 'Avez-vous mis en place des initiatives pour sensibiliser vos travailleur·euses à la réduction, la gestion et le recyclage des déchets ?'),
('ESG', '3. DÉCHETS', '3.1. DÉCHETS', 'Quelle(s) pratique(s) XXX a-t-elle mise(s) en place en matière d''économie circulaire pour limiter la production de déchets ?'),

-- 4. ÉCOSYSTÈMES ET BIODIVERSITÉ
('ESG', '4. ÉCOSYSTÈMES ET BIODIVERSITÉ', '4.1. ÉCOSYSTÈMES ET BIODIVERSITÉ', 'XXX a-t-elle mis en place une ou plusieurs initiatives visant à protéger les écosystèmes et préserver la biodiversité ?'),
('ESG', '4. ÉCOSYSTÈMES ET BIODIVERSITÉ', '4.1. ÉCOSYSTÈMES ET BIODIVERSITÉ', 'Proposez-vous des ateliers de sensibilisation et des formations sur biodiversité à destination de vos travailleur·euses ?'),

-- 5. DIVERSITE, INCLUSION ET EQUITE
('ESG', '5. DIVERSITE, INCLUSION ET EQUITE', '5.1. INCLUSION ET EQUITE', 'Comment XXX crée-t-elle un processus de recrutement et d''embauche inclusif ?'),
('ESG', '5. DIVERSITE, INCLUSION ET EQUITE', '5.1. INCLUSION ET EQUITE', 'Comment XXX crée-t-elle un lieu de travail équitable et inclusif pour les travailleur·euses ?'),
('ESG', '5. DIVERSITE, INCLUSION ET EQUITE', '5.1. INCLUSION ET EQUITE', 'En dehors du règlement de travail légal, quelles sont la ou les pratiques suivantes que XXX a mis en oeuvre en matière de diversité et d''inclusion ?'),
('ESG', '5. DIVERSITE, INCLUSION ET EQUITE', '5.1. INCLUSION ET EQUITE', 'Est-ce que XXX monitore les formations en matière de diversité et d''inclusion ?'),
('ESG', '5. DIVERSITE, INCLUSION ET EQUITE', '5.1. INCLUSION ET EQUITE', 'La politique salariale de XXX est-elle régulièrement examinée pour s''assurer que les travailleur·euses bénéficient d''un traitement égal pour un travail égal ?'),
('ESG', '5. DIVERSITE, INCLUSION ET EQUITE', '5.1. INCLUSION ET EQUITE', 'Quel est le multiple du salaire de la personne la mieux rémunérée, y compris les primes, par rapport à celui de la personne à temps plein la moins bien rémunérée ?'),
('ESG', '5. DIVERSITE, INCLUSION ET EQUITE', '5.2. DIVERSITE', 'Quel pourcentage des travailleur·euses est âgé de moins de vingt-quatre ans ou de plus de cinquante ans ?'),
('ESG', '5. DIVERSITE, INCLUSION ET EQUITE', '5.2. DIVERSITE', 'Quel est le pourcentage des cadres de XXX qui s''identifient comme femmes ?'),
('ESG', '5. DIVERSITE, INCLUSION ET EQUITE', '5.2. DIVERSITE', 'Quel est le pourcentage des travailleur·euses de XXX qui s''identifient comme femmes ?'),
('ESG', '5. DIVERSITE, INCLUSION ET EQUITE', '5.2. DIVERSITE', 'Quel pourcentage des travailleur·euses se considère comme appartenant à un groupe social sous-représenté (ex : personnes LGBTQIA+, issues de minorités ethniques, etc.)'),
('ESG', '5. DIVERSITE, INCLUSION ET EQUITE', '5.2. DIVERSITE', 'Quel pourcentage des travailleur·euses de XXX fait partie d''un groupe souvent exclu du marché du travail (ex : personnes en situation de handicap, anciens détenus, jeunes demandeurs d''emploi, chômeurs de longue durée, etc.) ?'),

-- 6. SÉCURITÉ, SANTÉ & BIEN-ÊTRE
('ESG', '6. SÉCURITÉ, SANTÉ & BIEN-ÊTRE', '6.1. SECURITE AU TRAVAIL', 'Comment XXX démontre-t-elle son engagement à garantir la santé et la sécurité des travailleur·euses, en allant au-delà des obligations légales ?'),
('ESG', '6. SÉCURITÉ, SANTÉ & BIEN-ÊTRE', '6.1. SECURITE AU TRAVAIL', 'Est-ce que XXX mesure le taux d''accidents dans l''entreprise par année fiscale ? Si oui, veuillez préciser ce taux : Nombre d''accidents du travail au cours de l''année de référence/ Nombre total d''heures travaillées au cours d''une année par l''ensemble des salariés)*200 000. Indication : 1710 heures travaillées en 2023 pour un équivalent temps plein en Belgique (225*7,6)'),
('ESG', '6. SÉCURITÉ, SANTÉ & BIEN-ÊTRE', '6.2. SANTÉ ET BIEN-ÊTRE', 'Quelles initiatives ou politiques en matière de santé et de bien-être XXX propose-t-elle à ses travailleur·euses ?'),
('ESG', '6. SÉCURITÉ, SANTÉ & BIEN-ÊTRE', '6.2. SANTÉ ET BIEN-ÊTRE', 'Est-ce que XXX mesure le taux d''absentéisme dans l''entreprise par année fiscale ? Si oui, veuillez préciser ce taux : nombre de jours d''absentéisme/Nombre de jours de travail * nombre de salariés * 200 000'),

-- 7. EMPLOI ET PRATIQUES DE TRAVAIL
('ESG', '7. EMPLOI ET PRATIQUES DE TRAVAIL', '7.1. DEVELOPPEMENT DES COMPETENCES', 'Est-ce que XXX a mis en place une politique de formation des travailleur·euses qui prévoit un certain nombre d''heures de formation et/ou un budget annuel par travailleur·euse ?'),
('ESG', '7. EMPLOI ET PRATIQUES DE TRAVAIL', '7.1. DEVELOPPEMENT DES COMPETENCES', 'Est-ce que XXX offre aux travailleur·euses l''une des possibilités de formation suivantes en vue de leur développement professionnel ?'),
('ESG', '7. EMPLOI ET PRATIQUES DE TRAVAIL', '7.1. DEVELOPPEMENT DES COMPETENCES', 'Est-ce que XXX mesure le pourcentage de travailleur·euses ayant bénéficié d''une formation au cours des 12 derniers mois ? Si oui, veuillez préciser ce pourcentage.'),
('ESG', '7. EMPLOI ET PRATIQUES DE TRAVAIL', '7.1. DEVELOPPEMENT DES COMPETENCES', 'Quel est le montant total des dépenses consacrées à la formation des travailleur·euses au cours de la dernière année fiscale ?'),
('ESG', '7. EMPLOI ET PRATIQUES DE TRAVAIL', '7.1. DEVELOPPEMENT DES COMPETENCES', 'Quel est le pourcentage de travailleur·euses ayant bénéficié d''une promotion interne au cours des 12 derniers mois ?'),
('ESG', '7. EMPLOI ET PRATIQUES DE TRAVAIL', '7.1. DEVELOPPEMENT DES COMPETENCES', 'Comment est-ce que XXX engage et responsabilise les travailleur·euses ?'),
('ESG', '7. EMPLOI ET PRATIQUES DE TRAVAIL', '7.2. ENGAGEMENT ET SATISFACTION', 'Lesquelles des affirmations suivantes sont vraies en ce qui concerne la satisfaction et/ou l''engagement des travailleur·euses au sein de XXX ?'),
('ESG', '7. EMPLOI ET PRATIQUES DE TRAVAIL', '7.2. ENGAGEMENT ET SATISFACTION', 'Quel est le pourcentage équivalent du chiffre d''affaires distribué aux travailleur·euses sous forme de prime au cours du dernier exercice fiscal ?'),
('ESG', '7. EMPLOI ET PRATIQUES DE TRAVAIL', '7.2. ENGAGEMENT ET SATISFACTION', 'Quel est le pourcentage de travailleur·euses ayant bénéficié d''une prime au cours du dernier exercice fiscal ?'),
('ESG', '7. EMPLOI ET PRATIQUES DE TRAVAIL', '7.2. ENGAGEMENT ET SATISFACTION', 'Quel est le pourcentage de vos travailleur·euses qui sont "Satisfait·es" ou "Engagé·es" ?'),
('ESG', '7. EMPLOI ET PRATIQUES DE TRAVAIL', '7.2. ENGAGEMENT ET SATISFACTION', 'Quel est le turn-over en pourcentage de XXX ? (Sur l''année fiscale précédente, diviser le nombre de départs d''employés (volontaires ou non) par l''effectif moyen de l''entreprise, puis multiplier le résultat par 100 pour obtenir un pourcentage)'),

-- 8. ENGAGEMENT CIVIQUE
('ESG', '8. ENGAGEMENT CIVIQUE', '8.1. ENGAGEMENT SOCIAL', 'Comment XXX s''implique-t-elle dans des projets sociaux ?'),
('ESG', '8. ENGAGEMENT CIVIQUE', '8.1. ENGAGEMENT SOCIAL', 'Est-ce que XXX monitore régulièrement les heures consacrées à l''engagement social ?'),
('ESG', '8. ENGAGEMENT CIVIQUE', '8.2. PHILANTHROPIE', 'Comment XXX aborde-t-elle la philanthropie ?'),
('ESG', '8. ENGAGEMENT CIVIQUE', '8.2. PHILANTHROPIE', 'Quel est le pourcentage du chiffre d''affaires distribué à titre philanthropique au cours du dernier exercice fiscal ?'),

-- 9. CONDUITE DES AFFAIRES
('ESG', '9. CONDUITE DES AFFAIRES', '9.1. STRUCTURE DE GOUVERNANCE', 'Laquelle de ces options décrit le mieux la structure de gouvernance de XXX ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.1. STRUCTURE DE GOUVERNANCE', 'Le conseil d''administration de XXX dispose-t-il de sièges avec droit de vote représentant :'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.1. STRUCTURE DE GOUVERNANCE', 'Combien de membres compte votre conseil d''administration au total ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.1. STRUCTURE DE GOUVERNANCE', 'Quel est le pourcentage d''administateur·rices indépendant·es au sein de votre conseil d''administration ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.1. STRUCTURE DE GOUVERNANCE', 'Quel est le pourcentage des membres de votre conseil d''administration qui s''identifient comme femmes ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.1. STRUCTURE DE GOUVERNANCE', 'Tous·tes les membres du conseil d''administration et de la direction remplissent-ils·elles un questionnaire annuel sur les conflits d''intérêts ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.1. STRUCTURE DE GOUVERNANCE', 'Combien de réunions du conseil d''administration avez-vous tenues au cours des 12 derniers mois ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.2. INTEGRATION DES PARTIES PRENANTES', 'Quel pourcentage des principaux fournisseurs fait l''objet d''audits ou contrôles annuels d''assurance qualité ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.2. INTEGRATION DES PARTIES PRENANTES', 'Parmi les initiatives suivantes, quelles sont celles qui ont été mises en oeuvre par XXX pour atténuer les risques ESG au sein de sa chaîne d''approvisionnement ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.2. INTEGRATION DES PARTIES PRENANTES', 'XXX met-elle en place une ou plusieurs des actions suivantes pour gérer la valeur qu''elle apporte à ses client·es ou consommateur·rices ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.2. INTEGRATION DES PARTIES PRENANTES', 'Comment XXX intègre-t-elle les performances sociales et environnementales dans son processus décisionnel ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.3. GESTION DURABLE', 'Avez-vous une mission formelle et écrite qui comprend l''un des élements suivants ? 
Une déclaration de mission formelle et écrite de l''entreprise est une déclaration publique ou formellement partagée avec les travailleur·euses de l''entreprise.'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.3. GESTION DURABLE', 'Comment XXX intègre-t-elle les Objectifs de Développement Durables (ODD) dans sa stratégie globale et ses activités commerciales ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.3. GESTION DURABLE', 'Quelles sont les étapes suivantes de l''analyse de double matérialité de XXX que vous avez déjà mises en oeuvres ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.4. TRANSPARENCE', 'Quelles informations sur son impact environnemental XXX rend-elle accessibles et transparentes ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.4. TRANSPARENCE', 'Quelles informations sur son impact social XXX rend-elle accessibles et transparentes ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.4. TRANSPARENCE', 'Quelles informations sur sa gouvernance XXX rend-elle accessibles et transparentes ?'),
('ESG', '9. CONDUITE DES AFFAIRES', '9.4. TRANSPARENCE', 'Quelles actions XXX a-t-elle mises en place pour garantir la qualité de son rapport d''impact ?'),

-- 10. ETHIQUE DES AFFAIRES
('ESG', '10. ETHIQUE DES AFFAIRES', '10.1. FORMALISATION DES PRATIQUES', 'Quelle est l''approche de XXX en matière de formalisation de ses engagements : avez-vous écrit et partagé en interne les politiques suivantes ?'),
('ESG', '10. ETHIQUE DES AFFAIRES', '10.2. LUTTE CONTRE LA CORRUPTION FINANCIÈRE', 'Le programme de lutte contre la corruption de XXX inclut-il un ou plusieurs des éléments suivants ?'),
('ESG', '10. ETHIQUE DES AFFAIRES', '10.3. DIVULGATION DES LITIGES', 'XXX a-t-elle été confrontée à un litige important au cours de l''année écoulée (Si oui, veuillez préciser) ?'),
('ESG', '10. ETHIQUE DES AFFAIRES', '10.3. DIVULGATION DES LITIGES', 'XXX a-t-elle été confrontée à un problème environnemental majeur ou à un litige au cours de l''année écoulée. (Si oui, veuillez préciser) ?'),

-- 11. PROTECTION DES DONNEES
('ESG', '11. PROTECTION DES DONNEES', '11.1. SECURITE DES DONNEES', 'Parmi les initiatives suivantes, laquelle ou lesquelles ont été mises en œuvre pour assurer la protection des données ?'),
('ESG', '11. PROTECTION DES DONNEES', '11.2. PROTECTION DE LA VIE PRIVEE', 'Laquelle de ces propositions décrit le mieux l''état de votre politique de protection de la vie privée des employé·es et client·es ?'),
('ESG', '11. PROTECTION DES DONNEES', '11.2. PROTECTION DE LA VIE PRIVEE', 'XXX respecte-t-elle toutes les obligations spécifiques du RGPD en ce qui concerne la collecte, l''utilisation et la protection des données  acquises par le biais de son site web. ?'),

-- 12. CERTIFICATIONS
('ESG', '12. CERTIFICATIONS', '12.1. CERTIFICATIONS D''UN PRODUIT, D''UN SERVICE OU D''UNE PRATIQUE', 'Quel est le pourcentage de vos produits ou services ou pratiques durables qui ont été contrôlés et certifiés par un organisme d''accréditation  axé sur la qualité ou le développement durable ? (ex : Fairtrade, BIO, Ecovadis, Ethibel, BDO etc) '),
('ESG', '12. CERTIFICATIONS', '12.2. CERTIFICATIONS DE L''ENTREPRISE', 'XXX a-t-elle obtenu une ou plusieurs certifications attestant ses efforts en matière de transition durable ?');

INSERT INTO pfe.answers_esg (answer, template, question_id, score_now, score_commitment_pact, is_forced_engagement, is_forced_comment)
VALUES
-- 1. ENERGIE & CARBONE
('oui','ALL',1,2.0,0.5,FALSE, FALSE),
('Non', 'ALL', 1, 0.0, 0.0, FALSE, FALSE),
(NULL, 'ALL', 2, 0.0, 0.0, FALSE, TRUE);

INSERT INTO pfe.answers_esg (answer, template, question_id, score_now, score_commitment_pact, is_forced_engagement)
VALUES
('Oui', 'OWNED FACILITY', 3, 1.0, 0.25, FALSE),
('Non', 'OWNED FACILITY', 3, 0.0, 0.0, FALSE),
('Je ne sais pas', 'OWNED FACILITY', 3, 0.0, 0.0, FALSE),
('Non applicable', 'OWNED FACILITY', 3, 0.0, 0.0, FALSE),
('Oui', 'OWNED FACILITY', 4, 1.0, 0.25, FALSE),
('Non', 'OWNED FACILITY', 4, 0.0, 0.0, FALSE),
('Je ne sais pas', 'OWNED FACILITY', 4, 0.0, 0.0, FALSE),
('Non applicable', 'OWNED FACILITY', 4, 0.0, 0.0, FALSE),
('Nous avons investi dans des équipements de bureau économes en énergie, notamment des ordinateurs, des imprimantes, etc.', 'OWNED FACILITY', 5, 1.0, 0.25, FALSE),
('Nous avons remplacé les ampoules traditionnelles par des ampoules LED à haut rendement énergétique afin de réduire la consommation d''électricité.', 'OWNED FACILITY', 5, 1.0, 0.25, FALSE),
('Nous avons installé des thermostats intelligents pour optimiser les systèmes de chauffage, de ventilation et de climatisation (CVC) en vue d''une meilleure efficacité énergétique.', 'OWNED FACILITY', 5, 1.0, 0.25, FALSE),
('Nous réalisons régulièrement des audits énergétiques afin d''identifier les points à améliorer et d''optimiser notre consommation d''énergie.', 'OWNED FACILITY', 5, 1.0, 0.25, FALSE),
('Nous avons installé des détecteurs de présence pour l''éclairage et les systèmes CVC afin d''ajuster automatiquement la consommation en fonction des niveaux d''occupation.', 'OWNED FACILITY', 5, 1.0, 0.25, FALSE),
('Autre : veuillez expliquer dans les commentaires', 'OWNED FACILITY', 5, 0, 0.0, FALSE),
('Aucune de ces réponses.', 'OWNED FACILITY', 5, 0.0, 0, FALSE),
('Non applicable', 'OWNED FACILITY', 5, 0.0, 0.0, FALSE),
('Oui', 'WORKERS', 6, 1.0, 0.25, FALSE),
('Non', 'WORKERS', 6, 0.0, 0, FALSE),
('Non applicable - Nous n''avons pas de travailleur·euses.', 'WORKERS', 6, 0.0, 0.0, FALSE),
('Oui, pour les Scopes 1 & 2 (les émissions de gaz à effet de serre directes et indirectes liées à notre consommation d''énergie).', 'ALL', 7, 0.5, 0.125, FALSE),
('Oui, pour le Scope 3 (toutes les émissions de GES indirectes liées à nos activités).', 'ALL', 7, 1.5, 0.375, FALSE),
('Non', 'ALL', 7, 0.0, 0.0, FALSE),
(NULL, 'ALL', 8, 0.0, 0.0, FALSE),
(NULL, 'ALL', 9, 0.0, 0.0, FALSE),
(NULL, 'ALL', 10, 0.0, 0.0, FALSE),
('Nous n''avons pas réalisé de rapport d''empreinte carbone.', 'ALL', 11, 0.0, 0.0, FALSE),
('Notre rapport d''empreinte carbone inclut une déclaration claire de notre engagement en faveur de la réduction de notre empreinte carbone.', 'ALL', 11, 0.42105263157894735, 0.10526315789473684, FALSE),
('Notre rapport d''empreinte carbone présente une une ventilation des émissions de carbone par source ou catégorie.', 'ALL', 11, 0.42105263157894735, 0.10526315789473684, FALSE),
('Notre rapport d''empreinte carbone décrit de manière transparente la méthodologie utilisée, le champ d''application, le processus de collecte de données, les hypothèses, les incertitudes et les limites du calcul.', 'ALL', 11, 0.42105263157894735, 0.10526315789473684, FALSE),
('Notre rapport d''empreinte carbone présente nos objectifs de réduction et décrit les mesures prises pour les atteindre.', 'ALL', 11, 0.42105263157894735, 0.10526315789473684, FALSE),
('Notre rapport d''empreinte carbone est conforme à la méthodologie Bilan Carbone® et/ou au GHG Protocol (il a été réalisé via un expert et/ou une plateforme agréé).', 'ALL', 11, 0.42105263157894735, 0.10526315789473684, FALSE),
('Nous partageons publiquement notre rapport d''empreinte carbone complet (en ce compris tous les points cochés ci-dessus).', 'ALL', 11, 0.42105263157894735, 0, FALSE),
('Non applicable', 'ALL', 11, 0.0, 0.0, FALSE),
('Nous incitons nos travailleur·euses à adopter des modes de transport plus durables pour se rendre au travail (marche, vélo, transports en commun, covoiturage, etc.) en mettant en place des mesures telles que l''installation de douches, des incitations financières, etc.', 'WORKERS', 12, 0.42105263157894735, 0.10526315789473684, FALSE),
('Nous choisissons en priorité des fournisseurs qui adoptent les meilleures pratiques en matière de durabilité.', 'ALL', 12, 0.42105263157894735, 0.10526315789473684, FALSE),
('Nous avons une politique d''achats responsables, qui formalise notre engagement à privilégier les matières premières recyclées ou renouvelables et à réduire les déchets à la source.', 'ALL', 12, 0.42105263157894735, 0.10526315789473684, FALSE),
('Autre : veuillez expliquer dans les commentaires', 'ALL', 12, 0, 0.0, FALSE),
('Aucune de ces réponses.', 'ALL', 12, 0.0, 0, FALSE),
('Non applicable', 'ALL', 12, 0.0, 0.0, FALSE),
('Oui', 'WORKERS', 13, 0.42105263157894735, 0.10526315789473684, FALSE),
('Non', 'WORKERS', 13, 0.0, 0, FALSE),
('Non applicable', 'WORKERS', 13, 0.0, 0.0, FALSE),
('Je ne sais pas', 'ALL', 14, 0.0, 0.0, FALSE),
('<20%', 'ALL', 14, 0.0, 0.0, FALSE),
('20-39%', 'ALL', 14, 0.21052631578947367, 0.05263157894736842, FALSE),
('40-59%', 'ALL', 14, 0.3157894736842105, 0.07894736842105263, FALSE),
('60%+', 'ALL', 14, 0.42105263157894735, 0, FALSE),
('Non applicable', 'ALL', 14, 0.0, 0.0, FALSE),
('Je ne sais pas', 'PRODUIT', 15, 0.0, 0.0, FALSE),
('<10%', 'PRODUIT', 15, 0.0, 0.0, FALSE),
('10-39%', 'PRODUIT', 15, 0.10526315789473684, 0.02631578947368421, FALSE),
('40-59%', 'PRODUIT', 15, 0.21052631578947367, 0.05263157894736842, FALSE),
('60-89%', 'PRODUIT', 15, 0.3157894736842105, 0.07894736842105263, FALSE),
('90%+', 'PRODUIT', 15, 0.42105263157894735, 0, FALSE),
('Non applicable', 'PRODUIT', 15, 0.0, 0.0, FALSE),
('Oui', 'PRODUIT', 16, 0.42105263157894735, 0.10526315789473684, FALSE),
('Non', 'PRODUIT', 16, 0.0, 0.0, FALSE),
('Difficile à mettre en place en raison de contraintes propres à mon secteur.', 'PRODUIT', 16, 0.0, 0, FALSE),
('Non applicable', 'PRODUIT', 16, 0.0, 0.0, FALSE),
('Nous intégrons des critères environnementaux dans nos contrats fournisseurs, afin de les inciter à adopter des pratiques durables.', 'ALL', 17, 0.42105263157894735, 0.10526315789473684, FALSE),
('Nous réalisons régulièrement des audits environnementaux afin d''évaluer les performances environnementales de nos fournisseurs.', 'ALL', 17, 0.42105263157894735, 0.10526315789473684, FALSE),
('Nous procédons à des audits environnementaux réguliers afin d''évaluer les performances écologiques de nos fournisseurs.', 'ALL', 17, 0.42105263157894735, 0.10526315789473684, FALSE),
('Nous incitons nos fournisseurs à opter pour des solutions de transport bas carbone pour la livraison des marchandises.', 'ALL', 17, 0.42105263157894735, 0.10526315789473684, FALSE),
('Nous entretenons un dialogue ouvert avec nos fournisseurs et encourageons le partage des meilleures pratiques en matière de durabilité.', 'ALL', 17, 0.42105263157894735, 0.10526315789473684, FALSE),
('Nous travaillons en étroite collaboration avec les fournisseurs dès la phase de conception afin d''intégrer notamment les principes d''éco-conception, favorisant la durabilité et la recyclabilité.', 'ALL', 17, 0.42105263157894735, 0.10526315789473684, FALSE),
('Autre : veuillez expliquer dans les commentaires', 'ALL', 17, 0, 0.0, FALSE),
('Aucune de ces réponses.', 'ALL', 17, 0.0, 0, FALSE),
('Non applicable', 'ALL', 17, 0.0, 0.0, FALSE),

-- 2. EAU, MATIERES PREMIERES ET FOURNITURES
('Oui', 'FACILITY', 18, 2.0, 0.5, FALSE),
('Non', 'FACILITY', 18, 0.0, 0, FALSE),
('Non applicable', 'FACILITY', 18, 0.0, 0.0, FALSE),
(NULL, 'FACILITY', 19, 0.0, 0.0, FALSE),
('Nous avons installé des appareils à faible débit et/ou économes en eau.', 'FACILITY', 20, 0.8888888888888888, 0.2222222222222222, FALSE),
('Nous avons installé des systèmes de détection des fuites.', 'FACILITY', 20, 0.8888888888888888, 0.2222222222222222, FALSE),
('Nous avons mis en place des systèmes de récupération d''eau de pluie.', 'FACILITY', 20, 0.8888888888888888, 0.2222222222222222, FALSE),
('Nous effectuons régulièrement des audits de notre consommation d''eau pour repérer les zones à forte consommation et les éventuelles inefficacités.', 'FACILITY', 20, 0.8888888888888888, 0.2222222222222222, FALSE),
('Nous avons établi des lignes directrices pour encourager une consommation responsable et rationnelle de l''eau.', 'FACILITY', 20, 0.8888888888888888, 0.2222222222222222, FALSE),
('Autre : veuillez expliquer dans les commentaires', 'FACILITY', 20, 0, 0.0, FALSE),
('Aucune de ces réponses.', 'FACILITY', 20, 0.0, 0, FALSE),
('Non applicable', 'FACILITY', 20, 0.0, 0.0, FALSE),
('Oui', 'WORKERS', 21, 0.8888888888888888, 0.2222222222222222, TRUE),
('Non', 'WORKERS', 21, 0.0, 0, FALSE),
('Non applicable - Nous n''avons pas de travailleur·euses.', 'WORKERS', 21, 0.0, 0.0, FALSE),
('Nous avons réalisé une analyse de notre chaîne de valeur, incluant nos fournisseurs, services et matériaux, afin de repérer les principaux domaines où l''eau est utilisée.', 'ALL', 22, 0.8888888888888888, 0.2222222222222222, FALSE),
('Nous avons défini des objectifs pour réduire l''empreinte hydrique de notre chaîne d''approvisionnement.', 'ALL', 22, 0.8888888888888888, 0.2222222222222222, FALSE),
('Nous collaborons avec nos fournisseurs et les encourageons à collecter des données et à publier leur empreinte hydrique.', 'ALL', 22, 0.8888888888888888, 0.2222222222222222, FALSE),
('Autre : veuillez expliquer dans les commentaires', 'ALL', 22, 0, 0.0, FALSE),
('Aucune de ces réponses.', 'ALL', 22, 0.0, 0, FALSE),
('Non applicable', 'ALL', 22, 0.0, 0.0, FALSE),
('Nous avons effectué une étude approfondie de nos produits dans le but d''identifier les opportunités d''amélioration dans l''utilisation des ressources (exemple : analyse de cycle de vie).', 'PRODUIT', 23, 2.0, 0.5, FALSE),
('Nous investissons dans des technologies et des pratiques plus économes en ressources, et explorons de nouvelles possibilités de réduire l''utilisation des ressources.', 'PRODUIT', 23, 2.0, 0.5, FALSE),
('Nous partageons de manière transparente l''origine et notre utilisation de matières premières et/ou de nos fournitures.', 'PRODUIT', 23, 2.0, 0.5, FALSE),
('Autre : veuillez expliquer dans les commentaires', 'PRODUIT', 23, 0, 0.0, FALSE),
('Aucune des réponses ci-dessous.', 'PRODUIT', 23, 0.0, 0, FALSE),
('Non applicable', 'PRODUIT', 23, 0.0, 0.0, FALSE),
('Oui', 'WORKERS', 24, 2.0, 0.5, FALSE),
('Non', 'WORKERS', 24, 0.0, 0, FALSE),
('Non applicable', 'WORKERS', 24, 0.0, 0.0, FALSE),
('Je ne sais pas', 'PRODUIT', 25, 0.0, 0.0, FALSE),
('< 20%', 'PRODUIT', 25, 0.0, 0.0, FALSE),
('20-49%', 'PRODUIT', 25, 0.5, 0.125, FALSE),
('50-74%', 'PRODUIT', 25, 1.0, 0.25, FALSE),
('75-99%', 'PRODUIT', 25, 1.5, 0.375, FALSE),
('100%', 'PRODUIT', 25, 2.0, 0.5, FALSE),
('Non applicable', 'PRODUIT', 25, 0, 0.0, FALSE),

-- 3. DÉCHETS
('Oui', 'FACILITY', 26, 2.0, 0.5, FALSE),
('Non', 'FACILITY', 26, 0.0, 0, FALSE),
('Non applicable', 'FACILITY', 26, 0.0, 0.0, FALSE),
(NULL, 'FACILITY', 27, 0.0, 0.0, FALSE),
(NULL, 'FACILITY', 28, 0.0, 0.0, FALSE),
('Nous avons des programmes de recyclage couvrant au minimum le papier et le carton, les PMC, le verre et les déchets organiques.', 'FACILITY', 29, 0, 0.0, TRUE),
('Nous avons identifier au sein de l''organisation une personne responsable de la gestion des déchets (réduction, tri et éliminiation).', 'FACILITY', 29, 0.6153846153846154, 0.15384615384615385, FALSE),
('Nous mettons en place des systèmes efficaces de collecte pour les matériaux recyclables, en partenariat avec des fournisseurs spécialisés dans le recyclage.', 'FACILITY', 29, 0.6153846153846154, 0.15384615384615385, FALSE),
('Nous avons établi des lignes directrices pour l''élimination responsable des déchets qui ne peuvent être recyclés ou récupérés, en veillant au respect des réglementations et des normes applicables en matière d''élimination des déchets.', 'FACILITY', 29, 0.6153846153846154, 0.15384615384615385, TRUE),
('Nous mettons à disposition des articles réutilisables, tels que des tasses, des verres et des ustensiles, pour réduire l''usage de plastique jetable.', 'FACILITY', 29, 0.6153846153846154, 0.15384615384615385, TRUE),
('Nous privilégions l''achat de produits et de fournitures de bureau en vrac ou avec un emballage réduit au minimum, afin de limiter les déchets d''emballage.', 'FACILITY', 29, 0.6153846153846154, 0.15384615384615385, TRUE),
('Nous favorisons l''achat de produits rechargeables, comme les cartouches d''encre et les piles, afin de limiter notre production de déchets.', 'FACILITY', 29, 0.6153846153846154, 0.15384615384615385, TRUE),
('Nous privilégions les options de don ou de réutilisation, plutôt que de jeter, pour des articles tels que les meubles ou les équipements.', 'FACILITY', 29, 0.6153846153846154, 0.15384615384615385, TRUE),
('Autre : veuillez expliquer dans les commentaires', 'FACILITY', 29, 0, 0.0, FALSE),
('Aucune de ces réponses.', 'FACILITY', 29, 0.0, 0, FALSE),
('Non applicable', 'FACILITY', 29, 0.0, 0.0, FALSE),
('Oui', 'WORKERS', 30, 0.6153846153846154, 0.15384615384615385, TRUE),
('Non', 'WORKERS', 30, 0.0, 0, FALSE),
('Non applicable - Nous n''avons pas de travailleur·euses.', 'WORKERS', 30, 0.0, 0.0, FALSE),
('Nous réutilisons les déchets générés au cours des processus de fabrication.', 'PRODUIT', 31, 0.6153846153846154, 0.15384615384615385, FALSE),
('Nous avons pris des mesures pour simplifier le recyclage ou la réutilisation de nos produits.', 'PRODUIT', 31, 0.6153846153846154, 0.15384615384615385, FALSE),
('Nous disposons de programmes de reprise des produits en fin de vie.', 'PRODUIT', 31, 0.6153846153846154, 0.15384615384615385, FALSE),
('Nous réalisons régulièrement des audits de notre production de déchets pour repérer les principales sources, les possibilités d''amélioration et les opportunités de réduction.', 'PRODUIT', 31, 0.6153846153846154, 0.15384615384615385, FALSE),
('Nous sensibilisons les travailleur·euses et/ou les consommateur·rices aux principes et aux avantages de l''économie circulaire. ', 'PRODUIT', 31, 0.6153846153846154, 0.15384615384615385, FALSE),
('Autre : veuillez expliquer dans les commentaires', 'PRODUIT', 31, 0, 0.0, FALSE),
('Aucune de ces réponses.', 'PRODUIT', 31, 0.0, 0, FALSE),
('Non applicable', 'PRODUIT', 31, 0.0, 0.0, FALSE),

-- 4. ÉCOSYSTÈMES ET BIODIVERSITÉ
('Nous avons réalisé une analyse des impacts potentiels de nos activités sur la biodiversité.', 'PRODUIT', 32, 2.0, 0.5, FALSE),
('Nous avons mis en place des actions pour préserver et améliorer la biodiversité (comme la plantation d''arbres, de végétaux locaux ou la création de refuges pour la faune).', 'PRODUIT', 32, 1.3333333333333333, 0.3333333333333333, FALSE),
('Nous avons créé ou restauré des espaces naturels (par exemple, en réaménageant des zones dégradées ou en favorisant la végétation locale).', 'PRODUIT', 32, 1.3333333333333333, 0.3333333333333333, FALSE),
('Nous limitons fortement l''utilisation de produits nocifs pour la biodiversité (tels que les pesticides ou les engrais chimiques).', 'PRODUIT', 32, 1.3333333333333333, 0.3333333333333333, FALSE),
('Nous veillons à une gestion responsable et durable des terres (en réduisant les impacts liés à l''aménagement ou à l''exploitation et en préservant la qualité des sols).', 'PRODUIT', 32, 1.3333333333333333, 0.3333333333333333, FALSE),
('Nous avons formalisé notre engagement envers la protection des écosystèmes et de la biodiversité.', 'PRODUIT', 32, 1.3333333333333333, 0.3333333333333333, FALSE),
('Autre : veuillez expliquer dans les commentaires', 'PRODUIT', 32, 0, 0.0, FALSE),
('Aucune de ces réponses.', 'PRODUIT', 32, 0.0, 0, FALSE),
('N/A', 'PRODUIT', 32, 0.0, 0.0, FALSE),
('Oui', 'WORKERS', 33, 1.3333333333333333, 0.3333333333333333, FALSE),
('Non', 'WORKERS', 33, 0.0, 0, FALSE),
('Non applicable - Nous n''avons pas de travailleur·euses.', 'WORKERS', 33, 0.0, 0.0, FALSE),

-- 5. DIVERSITE, INCLUSION ET EQUITE
('Nous incluons dans toutes nos offres d''emploi une déclaration d''engagement en faveur de la diversité, de l''équité et de l''inclusion.', 'WORKERS', 34, 0.7272727272727273, 0.18181818181818182, TRUE),
('Nous analysons la formulation et les exigences de nos descriptions de poste pour nous assurer qu''elles sont inclusives et équitables.', 'WORKERS', 34, 0.7272727272727273, 0.18181818181818182, TRUE),
('Nous recrutons activement par l''intermédiaire d''organisations ou de services qui s''adressent à des personnes souvent exclues du marché du travail (ex : personnes en situation de handicap, personnes qui ont été incarcérées, demandeurs d''emploi jeunes ou de longue durée, etc.)', 'WORKERS', 34, 0.7272727272727273, 0.18181818181818182, FALSE),
('Nous procédons à des examens anonymes ou "à l''aveugle" des candidatures ou des CV sans y associer de noms ou de caractéristiques identifiables.', 'WORKERS', 34, 0.7272727272727273, 0.18181818181818182, FALSE),
('Autre : veuillez expliquer dans les commentaires.', 'WORKERS', 34, 0, 0.0, FALSE),
('Rien de tout cela.', 'WORKERS', 34, 0.0, 0.0, FALSE),
('Non applicable - Nous n''avons jamais recruté.', 'WORKERS', 34, 0, 0.0, FALSE),
('Nous avons désigné une personne ou un groupe explicitement responsable de la diversité, de l''équité et de l''inclusion.', 'WORKERS', 35, 0.7272727272727273, 0.18181818181818182, FALSE),
('Nous proposons des formations à tous·tes les travailleur·euses sur des sujets liés à la diversité, à l''équité et à l''inclusion.', 'WORKERS', 35, 0.7272727272727273, 0.18181818181818182, FALSE),
('Nos installations sont conçues pour répondre aux exigences d''accessibilité pour les personnes souffrant d''un handicap physique.', 'WORKERS', 35, 0.7272727272727273, 0.18181818181818182, FALSE),
('Autre : veuillez expliquer dans les commentaires.', 'WORKERS', 35, 0, 0.0, FALSE),
('Rien de tout cela.', 'WORKERS', 35, 0.0, 0, FALSE),
('Non applicable', 'WORKERS', 35, 0.0, 0.0, FALSE),
('Une affirmation claire et explicite de l''engagement de l''organisation envers la non-discrimination et l''égalité de traitement pour tous·tes, indépendamment de l''origine, de l''ethnie, du genre, de l''orientation sexuelle, du handicap, de l''âge, de la religion ou de toute autre considération qui limiterait l''inclusion et l''équité.', 'WORKERS', 36, 0.7272727272727273, 0.18181818181818182, FALSE),
('Identification des rôles et des responsabilités pour établir un lieu de travail inclusif et créer l''implication de tous·tes à tous les niveaux.', 'WORKERS', 36, 0.7272727272727273, 0.18181818181818182, FALSE),
('Mise en œuvre de programmes visant à sensibiliser les travailleur·euses aux biais inconscients, à renforcer leurs compétences culturelles et à promouvoir des comportements inclusifs pour une culture d''inclusion active. ', 'WORKERS', 36, 0.7272727272727273, 0.18181818181818182, FALSE),
('Autre : veuillez expliquer dans les commentaires.', 'WORKERS', 36, 0, 0.0, FALSE),
('Rien de tout cela.', 'WORKERS', 36, 0.0, 0, FALSE),
('Non applicable', 'WORKERS', 36, 0.0, 0.0, FALSE),
('Oui, nous nous assurons que chaque travailleur·euse ait suivi une formation sur la diversité et l''inclusion.', 'WORKERS', 37, 0.2857142857142857, 0.07142857142857142, FALSE),
('Non', 'WORKERS', 37, 0.0, 0, FALSE),
('Non applicable', 'WORKERS', 37, 0.0, 0.0, FALSE),
('Oui', 'WORKERS', 38, 0.7272727272727273, 0.18181818181818182, FALSE),
('Non', 'WORKERS', 38, 0.0, 0, FALSE),
('Non applicable', 'WORKERS', 38, 0.0, 0.0, FALSE),
('Je ne sais pas.', 'WORKERS', 39, 0.0, 0.0, FALSE),
('>15x plus élevé', 'WORKERS', 39, 0.0, 0.0, FALSE),
('11-15x plus élevé', 'WORKERS', 39, 0.14285714285714285, 0.03571428571428571, FALSE),
('6-10x plus élevé', 'WORKERS', 39, 0.21428571428571427, 0.05357142857142857, FALSE),
('1-5x plus élevé', 'WORKERS', 39, 0.2857142857142857, 0, FALSE),
('Non applicable', 'WORKERS', 39, 0.0, 0.0, FALSE),
('0%', 'WORKERS', 40, 0.0, 0.0, FALSE),
('1-14%', 'WORKERS', 40, 0.14285714285714285, 0.03571428571428571, FALSE),
('15-29%', 'WORKERS', 40, 0.21428571428571427, 0.05357142857142857, FALSE),
('30%+', 'WORKERS', 40, 0.2857142857142857, 0.07142857142857142, FALSE),
('Je ne sais pas.', 'WORKERS', 40, 0.0, 0, FALSE),
('Non applicable', 'WORKERS', 40, 0.0, 0.0, FALSE),
('0%', 'WORKERS', 41, 0.0, 0.0, FALSE),
('1-24%', 'WORKERS', 41, 0.14285714285714285, 0.03571428571428571, FALSE),
('25-49%', 'WORKERS', 41, 0.21428571428571427, 0.05357142857142857, FALSE),
('50%+', 'WORKERS', 41, 0.2857142857142857, 0.07142857142857142, FALSE),
('Je ne sais pas.', 'WORKERS', 41, 0.0, 0.0, FALSE),
('Non applicable - Nous n''avons pas de cadre.', 'WORKERS', 41, 0.0, 0.0, FALSE),
('0%', 'WORKERS', 42, 0.0, 0.0, FALSE),
('1-24%', 'WORKERS', 42, 0.14285714285714285, 0.03571428571428571, FALSE),
('25-49%', 'WORKERS', 42, 0.21428571428571427, 0.05357142857142857, FALSE),
('50%+', 'WORKERS', 42, 0.2857142857142857, 0.07142857142857142, FALSE),
('Je ne sais pas.', 'WORKERS', 42, 0.0, 0, FALSE),
('Non applicable', 'WORKERS', 42, 0.0, 0.0, FALSE),
('0%', 'WORKERS', 43, 0.0, 0.0, FALSE),
('1-14%', 'WORKERS', 43, 0.14285714285714285, 0.03571428571428571, FALSE),
('15-29%', 'WORKERS', 43, 0.21428571428571427, 0.05357142857142857, FALSE),
('30%+', 'WORKERS', 43, 0.2857142857142857, 0.07142857142857142, FALSE),
('Je ne sais pas.', 'WORKERS', 43, 0.0, 0, FALSE),
('Non applicable', 'WORKERS', 43, 0.0, 0.0, FALSE),
('0%', 'WORKERS', 44, 0.0, 0.0, FALSE),
('1-14%', 'WORKERS', 44, 0.14285714285714285, 0.03571428571428571, FALSE),
('15-29%', 'WORKERS', 44, 0.21428571428571427, 0.05357142857142857, FALSE),
('30%+', 'WORKERS', 44, 0.2857142857142857, 0.07142857142857142, FALSE),
('Je ne sais pas.', 'WORKERS', 44, 0.0, 0, FALSE),
('Non applicable', 'WORKERS', 44, 0.0, 0.0, FALSE),

-- 6. SÉCURITÉ, SANTÉ & BIEN-ÊTRE
('Nous élaborons et communiquons des politiques claires en matière de sécurité, facilement accessibles.', 'WORKERS', 45, 1.43, 0.36, FALSE),
('Nous élaborons et communiquons des politiques claires de lutte contre le harcèlement et la violence, décrivant les comportements inacceptables et les conséquences en cas d''infraction.', 'WORKERS', 45, 1.43, 0.36, FALSE),
('Nous mettons en place en place des systèmes de signalement confidentiels et anonymes permettant aux travailleur·euses de signaler les incidents de harcèlement ou de violence sans crainte de représailles.', 'WORKERS', 45, 1.43, 0.36, FALSE),
('Nous définissons et communiquons des procédures claires pour l''examen des plaintes, en veillant à ce que les enquêtes soient approfondies et impartiales.', 'WORKERS', 45, 1.43, 0.36, FALSE),
('Nous mettons en œuvre des programmes de formation annuels pour apprendre aux travailleur·euses à reconnaître et à prévenir le harcèlement, la violence ou les comportements dangereux sur le lieu de travail.', 'WORKERS', 45, 1.43, 0.36, FALSE),
('Nous mettons à jour nos politiques de lutte contre le harcèlement et de gestion des plaintes et des incidents chaque année, et nous informons les travailleur·euses des ressources disponibles à cet égard.', 'WORKERS', 45, 1.43, 0.36, FALSE),
('Autre : veuillez expliquer dans les commentaires.', 'WORKERS', 45, 0.0, 0.0, FALSE),
('Aucune de ces réponses.', 'WORKERS', 45, 0.0, 0.0, FALSE),
('Non applicable', 'WORKERS', 45, 0.0, 0.0, FALSE),
('Non', 'WORKERS', 46, 0.0, 0.0, FALSE),
('Oui: A COMPLETER', 'WORKERS', 46, 1.43, 0.0, FALSE),
('Non applicable', 'WORKERS', 46, 0.0, 0.0, FALSE),
('Nous fournissons aux travailleur·euses des services de conseil en matière de santé comportementale, des ressources en ligne ou des programmes de soutien en matière de bien-être au travail.', 'WORKERS', 47, 1.67, 0.42, FALSE),
('Nous avons mis en place des politiques et des programmes visant à promouvoir la santé et le bien-être sur le lieu de travail.', 'WORKERS', 47, 1.67, 0.42, TRUE),
('Nous parrainons et encourageons les travailleur·euses à participer à des activités de santé et de bien-être pendant la semaine de travail (par exemple, des programmes de marche ou d''escalade).', 'WORKERS', 47, 1.67, 0.42, FALSE),
('Nous invitons les travailleur·euses à effectuer des évaluations des risques pour la santé ou à participer à des activités de santé et de bien-être (par exemple un abonnement subventionné à une salle de sport).', 'WORKERS', 47, 1.67, 0.42, FALSE),
('Plus de 25 % des travailleur·euses ont effectué une évaluation des risques pour la santé au cours des douze derniers mois.', 'WORKERS', 47, 1.67, 0.42, FALSE),
('Autre : veuillez expliquer dans les commentaires.', 'WORKERS', 47, 0.0, 0.0, FALSE),
('Aucune de ces réponses.', 'WORKERS', 47, 0.0, 0.0, FALSE),
('Non applicable', 'WORKERS', 47, 0.0, 0.0, FALSE),
('Non', 'WORKERS', 48, 0.0, 0.0, FALSE),
('Oui: A COMPLETER', 'WORKERS', 48, 1.67, 0.0, FALSE),
('Non applicable', 'WORKERS', 48, 0.0, 0.0, FALSE),

-- 7. EMPLOI ET PRATIQUES DE TRAVAIL
('Oui, nous avons un plan de formation.', 'WORKERS', 49, 1.0, 0.25, FALSE),
('Non', 'WORKERS', 49, 0.0, 0.0, FALSE),
('Non applicable', 'WORKERS', 49, 0.0, 0.0, FALSE),
('Nous disposons d''un processus formel d''intégration des nouveaux·elles travailleur·euses.', 'WORKERS', 50, 1.0, 0.25, FALSE),
('Nous encourageons les promotions internes et l''embauche pour des postes avancés (en publiant d''abord les offres d''emploi en interne).', 'WORKERS', 50, 1.0, 0.25, FALSE),
('Nous proposons des formations polyvalentes pour les avancements de carrière ou les transitions (par exemple, une formation en gestion pour les non-cadres).', 'WORKERS', 50, 1.0, 0.25, FALSE),
('Nous facilitons les opportunités de développement professionnel externe et disposons d''un budget à cet effet (participation à des conférences, formations en ligne, etc.)', 'WORKERS', 50, 1.0, 0.25, FALSE),
('Nous offrons des remboursements ou des programmes pour des formations continues certifiantes (par exemple, diplômes universitaires, licences professionnelles).', 'WORKERS', 50, 1.0, 0.25, FALSE),
('Autre : veuillez expliquer dans les commentaires.', 'WORKERS', 50, 0.0, 0.0, FALSE),
('Rien de tout cela.', 'WORKERS', 50, 0.0, 0.0, FALSE),
('Non applicable', 'WORKERS', 50, 0.0, 0.0, FALSE),
('0%', 'WORKERS', 51, 0.0, 0.0, FALSE),
('1-49%', 'WORKERS', 51, 0.17, 0.04, FALSE),
('50-62%', 'WORKERS', 51, 0.33, 0.08, FALSE),
('63-75%', 'WORKERS', 51, 0.5, 0.13, FALSE),
('>75%', 'WORKERS', 51, 0.67, 0.17, FALSE),
('Non', 'WORKERS', 51, 0.0, 0.0, FALSE),
('Non applicable', 'WORKERS', 51, 0.0, 0.0, FALSE),
('0€', 'WORKERS', 52, 0.0, 0.0, FALSE),
('Le montant suivant : A COMPLETER', 'WORKERS', 52, 0.0, 0.0, FALSE),
('Non applicable', 'WORKERS', 52, 0.67, 0.17, FALSE),
('0%', 'WORKERS', 53, 0.0, 0.0, FALSE),
('1-4%', 'WORKERS', 53, 0.33, 0.08, FALSE),
('5-14%', 'WORKERS', 53, 0.5, 0.13, FALSE),
('15%+', 'WORKERS', 53, 0.67, 0.17, FALSE),
('je ne sais pas.', 'WORKERS', 53, 0.0, 0.0, FALSE),
('Non applicable', 'WORKERS', 53, 0.0, 0.0, FALSE),
('Nous avons mis en place des processus permettant aux travailleur·euses de donner leur avis et de contribuer aux prises de décisions opérationnelles importantes et/ou stratégiques et/ou sur tout changement de pratique qui affecterait leurs habitudes de travail (exemples : team et management meetings).', 'WORKERS', 54, 1.0, 0.25, FALSE),
('Nous disposons de mécanismes formels de retour d''information pour répondre aux préoccupations et améliorer les pratiques de l''entreprise (retour sur les préoccupations et contributions).', 'WORKERS', 54, 1.0, 0.25, FALSE),
('Autre : veuillez expliquer dans les commentaires.', 'WORKERS', 54, 0.0, 0.0, FALSE),
('Rien de tout cela.', 'WORKERS', 54, 0.0, 0.0, FALSE),
('Non applicable', 'WORKERS', 54, 0.0, 0.0, FALSE),
('L''entreprise contrôle la satisfaction des travailleur·euses.', 'WORKERS', 55, 1.11, 0.28, FALSE),
('L''entreprise partage la satisfaction des travailleur·euses en interne.', 'WORKERS', 55, 1.11, 0.28, FALSE),
('L''entreprise partage la satisfaction des travailleur·euses publiquement.', 'WORKERS', 55, 1.11, 0.28, FALSE),
('L''entreprise a défini des objectifs en matière de satisfaction des travailleur·euses.', 'WORKERS', 55, 1.11, 0.28, FALSE),
('Au cours de l''année écoulée, l''entreprise a atteint les objectifs fixés en matière de satisfaction des travailleur·euses.', 'WORKERS', 55, 1.11, 0.28, FALSE),
('Rien de tout cela.', 'WORKERS', 55, 0.0, 0.0, FALSE),
('Non applicable', 'WORKERS', 55, 0.0, 0.0, FALSE),
('Pas de versement de bonus ou pas de plan de bonus.', 'WORKERS', 56, 0.0, 0.0, FALSE),
('<1%', 'WORKERS', 56, 0.28, 0.07, FALSE),
('1-2%', 'WORKERS', 56, 0.56, 0.14, FALSE),
('2-3%', 'WORKERS', 56, 0.83, 0.21, FALSE),
('>3%', 'WORKERS', 56, 1.11, 0.0, FALSE),
('Non applicable', 'WORKERS', 56, 0.0, 0.0, FALSE),
('0%', 'WORKERS', 57, 0.0, 0.0, FALSE),
('1-49%', 'WORKERS', 57, 0.28, 0.07, FALSE),
('50-62%', 'WORKERS', 57, 0.56, 0.14, FALSE),
('63-75%', 'WORKERS', 57, 0.83, 0.21, FALSE),
('>75%', 'WORKERS', 57, 1.11, 0.0, FALSE),
('Non applicable', 'WORKERS', 57, 0.0, 0.0, FALSE),
('<65%', 'WORKERS', 58, 0.0, 0.0, FALSE),
('65-80%', 'WORKERS', 58, 0.56, 0.14, FALSE),
('81-90%', 'WORKERS', 58, 0.83, 0.21, FALSE),
('90%+', 'WORKERS', 58, 1.11, 0.28, FALSE),
('Je ne sais pas.', 'WORKERS', 58, 0.0, 0.0, FALSE),
('Non applicable', 'WORKERS', 58, 0.0, 0.0, FALSE),
('<5%', 'WORKERS', 59, 1.1, 0.28, FALSE),
('<12%', 'WORKERS', 59, 0.83, 0.21, FALSE),
('<25%', 'WORKERS', 59, 0.56, 0.14, FALSE),
('<40%', 'WORKERS', 59, 0.28, 0.07, FALSE),
('40%+', 'WORKERS', 59, 0.0, 0.0, FALSE),
('Je ne sais pas.', 'WORKERS', 59, 0.0, 0.0, FALSE),
('Non applicable', 'WORKERS', 59, 0.0, 0.0, FALSE),

-- 8. ENGAGEMENT CIVIQUE
('Nous avons des partenariats avec des organisations caritatives.', 'ALL', 60, 0.53, 0.13, FALSE),
('Nous offrons des produits ou des services à prix réduit aux groupes défavorisés.', 'ALL', 60, 0.53, 0.13, FALSE),
('Nous nous engageons dans des projets innovants au sein de notre communauté afin de résoudre des problèmes tels que la pauvreté, l''inégalité et la durabilité environnementale.', 'ALL', 60, 0.53, 0.13, FALSE),
('Nous investissons dans des projets d''entreprenariat social qui cherchent à relever des défis sociaux grâce à des modèles d''entreprise durables, ou nous les soutenons.', 'ALL', 60, 0.53, 0.13, FALSE),
('Nous participons aux efforts de sensibilisation et nous nous engageons auprès des décideur·euses politiques pour aborder les problèmes systémiques et contribuer aux changements politiques.', 'ALL', 60, 0.53, 0.13, FALSE),
('Nous collaborons avec des ONG et des fondations établies pour soutenir des projets sociaux, en tirant parti de leur expertise et de leurs réseaux pour un plus grand impact.', 'ALL', 60, 0.53, 0.13, FALSE),
('Nous encourageons l''engagement social de nos travailleur·euses (par exemple en offrant du temps rémunéré pour le bénévolat ou en organisant des journées de teambuilding dédiées à des projets solidaires).', 'WORKERS', 60, 0.53, 0.13, FALSE),
('Autre, veuillez décrire dans les commentaires.', 'ALL', 60, 0.0, 0.0, FALSE),
('Aucune de ces réponses.', 'ALL', 60, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 60, 0.0, 0.0, FALSE),
('Non', 'ALL', 61, 0.0, 0.0, FALSE),
('Oui : veuillez indiquer le nombre d''heures A COMPLETER', 'ALL', 61, 1.0, 0.0, FALSE),
('Non applicable', 'ALL', 61, 0.0, 0.0, FALSE),
('Nous établissons des partenariats avec des organisations caritatives et sans but lucratif locales afin de leur apporter un soutien financier régulier, garantissant ainsi un impact positif constant sur la communauté locale.', 'ALL', 62, 0.53, 0.13, FALSE),
('Nous mettons en place un programme de jumelage des dons des travailleur·euses où l''entreprise égale les contributions des travailleur·euses aux œuvres de bienfaisance locales, doublant ainsi efficacement l''impact.', 'WORKERS', 62, 0.53, 0.13, FALSE),
('Nous contribuons à l''enrichissement des arts et de la culture locaux en soutenant, par des dons financiers, des théâtres, des musées ou des manifestations artistiques de la communauté.', 'ALL', 62, 0.53, 0.13, FALSE),
('Nous allouons des fonds à des projets d''aide humanitaire mondiale, en soutenant les efforts de secours dans les régions touchées par des catastrophes naturelles, des conflits ou des crises sanitaires.', 'ALL', 62, 0.53, 0.13, FALSE),
('Nous mettons en place un programme de subventions pour soutenir des projets consacrés à la conservation de l''environnement, aux pratiques durables et à la préservation de la biodiversité.', 'ALL', 62, 0.53, 0.13, FALSE),
('Nous soutenons des initiatives mondiales en matière d''éducation en faisant des dons à des organisations qui s''efforcent d''améliorer l''accès à une éducation de qualité dans les communautés défavorisées.', 'ALL', 62, 0.53, 0.13, FALSE),
('Nous allouons des fonds pour soutenir des initiatives de microfinance, permettant à des personnes dans les régions en développement de créer ou de développer de petites entreprises.', 'ALL', 62, 0.53, 0.13, FALSE),
('Nous contribuons à des organisations et à des projets consacrés à la défense des droits de l''homme, en abordant des questions telles que l''égalité des sexes, la justice raciale et l''équité sociale.', 'ALL', 62, 0.53, 0.13, FALSE),
('Autre, veuillez décrire dans les commentaires.', 'ALL', 62, 0.0, 0.0, FALSE),
('Aucune des réponses ci-dessus.', 'ALL', 62, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 62, 0.0, 0.0, FALSE),
('<1%', 'ALL', 63, 0.5, 0.13, FALSE),
('1-2%', 'ALL', 63, 0.7, 0.18, FALSE),
('>2%', 'ALL', 63, 1.0, 0.25, FALSE),
('Pas de philantropie', 'ALL', 63, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 63, 0.0, 0.0, FALSE),

-- 9. CONDUITE DES AFFAIRES
('Notre organisation est dirigée par ses fondateur·trices ou propriétaires uniquement.', 'ALL', 64, 0.0, 0.0, FALSE),
('Notre conseil d''administration est composé d''au moins un·e membre qui n''est pas un·e fondateur·trice ou un·e propriétaire de l''entreprise.', 'ALL', 64, 1.33, 0.33, FALSE),
('Notre conseil d''administration est composé d''au moins un·e membre représentant les travailleur·euses de l''entreprise.', 'ALL', 64, 1.33, 0.33, FALSE),
('Les travailleur·euses cadres et/ou non-cadres.', 'ALL', 65, 1.33, 0.33, FALSE),
('Une expertise locale et/ou sociale. Par exemple un·e représentant·e de parties prenantes stragégiques, d''une université locale, d''une organisation territoriale ou sans but lucratif.', 'ALL', 65, 1.33, 0.33, FALSE),
('Une expertise environnementale. Par exemple un·e expert·e en développement durable, un·e  expert·e scientifique, une organisation territoriale ou sans but lucratif.', 'ALL', 65, 1.33, 0.33, FALSE),
('Aucune de ces réponses.', 'ALL', 65, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 65, 0.0, 0.0, FALSE),
(NULL, 'ALL', 66, 0.0, 0.0, FALSE),
(NULL, 'ALL', 67, 0.0, 0.0, FALSE),
('0%', 'ALL', 68, 0.0, 0.0, FALSE),
('1-24%', 'ALL', 68, 0.4, 0.1, FALSE),
('25-49%', 'ALL', 68, 1.20, 0.30, FALSE),
('>50', 'ALL', 68, 2.0, 0.50, FALSE),
('Non applicable', 'ALL', 68, 0.0, 0.0, FALSE),
('Oui', 'ALL', 69, 1.33, 0.33, FALSE),
('Non', 'ALL', 69, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 69, 0.0, 0.0, FALSE),
(NULL, 'ALL', 70, 0.0, 0.0, FALSE),
('1-24%', 'ALL', 71, 0.50, 0.13, FALSE),
('25-49%', 'ALL', 71, 1.0, 0.25, FALSE),
('50-75%', 'ALL', 71, 1.5, 0.38, FALSE),
('>75%', 'ALL', 71, 2.0, 0.50, FALSE),
('Nous ne procédons à aucun contrôle ou audit de nos fournisseurs.', 'ALL', 71, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 71, 0.0, 0.0, FALSE),
('Nous intégrons des critères ESG dans la sélection des fournisseurs.', 'ALL', 72, 0.57, 0.14, FALSE),
('Nous intégrons des clauses ESG dans les contrats avec nos fournisseurs.', 'ALL', 72, 0.57, 0.14, FALSE),
('Nous collaborons avec avec nos fournisseurs pour améliorer leurs pratiques ESG.', 'ALL', 72, 0.57, 0.14, FALSE),
('Nous encourageons nos fournisseurs à faire preuve de transparence et à divulguer leurs performances en matière d''ESG.', 'ALL', 72, 0.57, 0.14, FALSE),
('Autre : veuillez expliquer dans les commentaires.', 'ALL', 72, 0.0, 0.0, FALSE),
('Aucune de ces réponses..', 'ALL', 72, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 72, 0.0, 0.0, FALSE),
('Nous proposons des garanties sur nos produits et services, ainsi que des politiques de protection adaptées.', 'ALL', 73, 0.57, 0.14, TRUE),
('Nous disposons d''une ou plusieurs certifications de qualité ou d''accréditations de tiers attestant de la qualité de nos produits ou services.', 'ALL', 73, 0.57, 0.14, FALSE),
('Nous avons mis en place des mécanismes formels assurant un contrôle rigoureux de la qualité de nos produits ou services.', 'ALL', 73, 0.57, 0.14, FALSE),
('Nous avons mis en place des mécanismes pour recueillir les retours d''information, gérer le service après-vente et traiter les réclamations.', 'ALL', 73, 0.57, 0.14, FALSE),
('Nous contrôlons la satisfaction des client·es ou des consommateur·rices.', 'ALL', 73, 0.57, 0.14, FALSE),
('L''entreprise offre une assistance en temps réel à ses client·es.', 'ALL', 73, 0.57, 0.14, FALSE),
('Autre : veuillez expliquer dans les commentaires.', 'ALL', 73, 0.0, 0.0, FALSE),
('Aucune de ces réponses.', 'ALL', 73, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 73, 0.0, 0.0, FALSE),
('Nous formons et sensibilisons nos dirigeant·es et travailleur·euses aux questions sociales et/ou environnementales importantes pour notre entreprise ou notre mission.', 'ALL', 74, 0.57, 0.14, FALSE),
('Nous intégrons explicitement les performances sociales et environnementales dans les descriptions de poste des cadres.', 'ALL', 74, 0.57, 0.14, FALSE),
('Nous incluons formellement les questions sociales et environnementales dans nos évaluations des performances.', 'ALL', 74, 0.57, 0.14, FALSE),
('Nous examinons, au sein du conseil d''administration, les performances sociales et environnementales.', 'ALL', 74, 0.57, 0.14, FALSE),
('Aucune de ces réponses.', 'ALL', 74, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 74, 0.0, 0.0, FALSE),
('Aucun engagement social ou environnemental.', 'ALL', 75, 0.0, 0.0, FALSE),
('Un engagement général en matière de responsabilité sociale ou environnementale (par exemple, préservation de l''environnement).', 'ALL', 75, 1.0, 0.25, FALSE),
('Un engagement en faveur d''un impact social positif spécifique (par exemple, politique de prix réduit pour une certaine catégorie de clients ayant moins facilement accès à vos services ou vos produits).', 'ALL', 75, 2.0, 0.50, FALSE),
('Un engagement en faveur d''un impact positif spécifique sur l''environnement (par exemple, modèle d''affaires basé sur la location, la réparation et/ou la réutilisation plutôt que sur l''achat et l''élimination).', 'ALL', 75, 2.0, 0.50, FALSE),
('Nous n''avons pas de mission écrite et formelle.', 'ALL', 75, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 75, 0.0, 0.0, FALSE),
('Nous sommes conscient·es des objectifs de développement durable (ODD) des Nations unies et de leur importance.', 'ALL', 76, 0.67, 0.17, TRUE),
('Nous sensibilisons nos travailleur·euses aux ODD et les impliquons dans la poursuite de ces objectifs.', 'ALL', 76, 0.67, 0.17, FALSE),
('Nous alignons les activités et les initiatives de l''entreprise sur des objectifs de développement durable spécifiques.', 'ALL', 76, 0.67, 0.17, FALSE),
('Nous disposons d''indicateurs de performance ou de mesures de réussite pour mesurer l''impact positif de l''entreprise sur les ODD.', 'ALL', 76, 0.67, 0.17, FALSE),
('Aucune de ces réponses.', 'ALL', 76, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 76, 0.0, 0.0, FALSE),
('Cartographie des parties prenantes : Nous avons identifié et classifié les parties prenantes internes et externes pouvant avoir un impact sur ou être affectées par nos décisions, telles que les employé·es, les actionnaires, les client·es, les régulateurs, les investisseurs, et les communautés locales.', 'ALL', 77, 0.67, 0.17, FALSE),
('Évaluation de la matérialité d''impact : Nous avons analysé les enjeux environnementaux, sociaux et de gouvernance (ESG) les plus importants pour l''entreprise, en termes d''impact sur la société et l''environnement.', 'ALL', 77, 0.67, 0.17, FALSE),
('Évaluation de la matérialité financière : Nous avons identifié les risques et opportunités liés aux enjeux ESG ayant un impact significatif sur les revenus, les coûts et la valeur de l''entreprise (inondations, sécheresse, grèves, etc.).', 'ALL', 77, 0.67, 0.17, FALSE),
('Rapport au conseil d''administration : Nous avons présenté les résultats de l''engagement des parties prenantes et des évaluations de matérialité au plus haut niveau de supervision de l''entreprise, tel que le conseil d''administration.', 'ALL', 77, 0.67, 0.17, FALSE),
('Analyse comparative : Nous avons réalisé une analyse comparative avec les pairs de l''industrie pour identifier les questions matérielles communes et les défis spécifiques à l''industrie qui devraient être abordés par l''entreprise.', 'ALL', 77, 0.67, 0.17, FALSE),
('Matrice de matérialité : Nous avons élaboré une matrice visuelle de matérialité qui illustre l''importance relative des différents enjeux ESG pour l''entreprise et ses parties prenantes, facilitant ainsi la priorisation des actions.', 'ALL', 77, 0.67, 0.17, FALSE),
('Collaboration avec des experts externes : Nous avons travaillé avec des experts externes en matière de durabilité pour auditer et valider nos analyses, assurant ainsi la crédibilité et l''exactitude des évaluations.', 'ALL', 77, 0.67, 0.17, FALSE),
('Intégration stratégique : Nous avons intégré les évaluations de la matérialité d''impact et financière dans la stratégie globale de l''entreprise, incluant les processus de gestion des risques et les plans d''action pour atténuer les risques identifiés.', 'ALL', 77, 0.67, 0.17, FALSE),
('Aucune de ces réponses.', 'ALL', 77, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 77, 0.0, 0.0, FALSE),
('Notre consommation d''énergie, notre stratégie et nos pratiques pour la réduire.', 'ALL', 78, 0.19, 0.05, FALSE),
('Notre empreinte carbone, notre stratégie et nos pratiques pour la réduire.', 'ALL', 78, 0.19, 0.05, FALSE),
('Notre politique d''achat responsable.', 'ALL', 78, 0.19, 0.05, FALSE),
('Notre consommation d''eau, notre stratégie et nos pratiques pour la réduire.', 'FACILITY', 78, 0.19, 0.05, FALSE),
('Notre production de déchets, notre stratégie et nos pratiques pour la réduire.', 'FACILITY', 78, 0.19, 0.05, FALSE),
('Notre stratégie en matière de circularité et/ou biodiversité.', 'ALL', 78, 0.19, 0.05, FALSE),
('L''impact de notre modèle d''affaires sur l''environnement.', 'ALL', 78, 0.19, 0.05, FALSE),
('Autre : veuillez expliquer dans les commentaires.', 'ALL', 78, 0.0, 0.0, FALSE),
('Aucune de ces réponses.', 'ALL', 78, 0.0, 0.0, FALSE),
('Notre politique et nos performances en matière de promotion de la diversité et de l''inclusion.', 'WORKERS', 79, 0.19, 0.05, FALSE),
('Notre politique et nos performances en matière de sécurité au travail.', 'WORKERS', 79, 0.19, 0.05, FALSE),
('Notre politique et nos performances en matière de promotion de la santé et du bien-être.', 'WORKERS', 79, 0.19, 0.05, FALSE),
('Notre politique et nos performances en matière d''engagement civique', 'ALL', 79, 0.19, 0.05, FALSE),
('L''impact de notre modèle d''affaires sur la société.', 'ALL', 79, 0.19, 0.05, FALSE),
('Notre politique de formation et de développement des compétences', 'WORKERS', 79, 0.19, 0.05, FALSE),
('Le taux de satisfaction ou d''engagement de nos équipes', 'WORKERS', 79, 0.19, 0.05, FALSE),
('Autre : veuillez expliquer dans les commentaires.', 'ALL', 79, 0.0, 0.0, FALSE),
('Aucune de ces réponses', 'ALL', 79, 0.0, 0.0, FALSE),
('La composition du conseil d''administration.', 'ALL', 80, 0.19, 0.05, FALSE),
('L''organigramme de l''équipe.', 'WORKERS', 80, 0.19, 0.05, FALSE),
('Les résultats financiers (au moins transparents pour les travailleur·euses).', 'ALL', 80, 0.19, 0.05, FALSE),
('La mission formelle et écrite.', 'ALL', 80, 0.19, 0.05, FALSE),
('L''intégration de nos parties prenantes dans la gestion et la stratégie d''impact (informations sur la manière dont l''entreprise engage le dialogue avec ses parties prenantes (client·es, employé·es, actionnaires, communautés locales), et comment nous intégrons leurs attentes dans notre stratégie.', 'ALL', 80, 0.19, 0.05, FALSE),
('Les Objectifs de Développement Durable auxquels nous contribuons directement et indirectement.', 'ALL', 80, 0.19, 0.05, FALSE),
('Notre politique en matière de gestion et de protection des données (site web : cookies, guide d''utilisation, RGPD).', 'ALL', 80, 0.19, 0.05, FALSE),
('Le taux de satisfaction de nos clients.', 'ALL', 80, 0.19, 0.05, FALSE),
('Autre : veuillez expliquer dans les commentaires.', 'ALL', 80, 0.0, 0.0, FALSE),
('Aucune de ces réponses.', 'ALL', 80, 0.0, 0.0, FALSE),
('Nous n''avons pas de rapport d''impact.', 'ALL', 81, 0.0, 0.0, FALSE),
('Élaborer un rapport complet de durabilité qui divulgue de manière transparente les impacts, les performances et les progrès de l''entreprise sur les questions importantes.', 'ALL', 81, 0.19, 0.05, FALSE),
('Élaborer un rapport intégré, qui combine les informations financières et de développement durable d''une manière holistique afin de fournir une image plus complète de la performance de l''entreprise.', 'ALL', 81, 0.19, 0.05, FALSE),
('Aligner les rapports sur le développement durable sur les objectifs de développement durable des Nations unies, en montrant comment les activités de l''entreprise contribuent à des objectifs mondiaux plus larges.', 'ALL', 81, 0.19, 0.05, TRUE),
('Obtenir l''assurance d''une tierce partie pour les rapports sur le développement durable afin de renforcer la crédibilité et de démontrer l''engagement de l''entreprise en faveur de la transparence.', 'ALL', 81, 0.19, 0.05, FALSE),

-- 10. ETHIQUE DES AFFAIRES

('Code de conduite éthique : déclaration écrite claire de la mission de l''organisation, ses valeurs et ses principes éthiques, sa politique de conduite éthique des affaires, le respect des droits de l''homme, les normes de travail équitables, sa politique pour adopter un comportement responsable à l''égard des parties prenantes, y compris les client·es, les travailleur·euses, les fournisseurs et les communautés locales.', 'ALL', 82, 0.42, 0.10, FALSE),
('Code de conduite interne : déclaration écrite sur les normes de conduite professionnelle attendues de tous·tes les travailleur·euses, y compris l''interdiction de comportements inappropriés tels que la fraude, la corruption, le harcèlement et la discrimination.', 'WORKERS', 82, 0.42, 0.10, FALSE),
('Charte sur les conflits d''intérêts : déclaration écrite des politiques d''identification et de gestion des conflits d''intérêts potentiels, et de divulgation transparente des relations financières et personnelles susceptibles d''influencer les décisions de l''entreprise.', 'ALL', 82, 0.42, 0.10, FALSE),
('Charte de lanceur d''alerte : déclaration écrite encadrant les modalités par lesquelles les employés ou parties prenantes peuvent signaler des comportements illégaux, contraires à l''éthique ou mettant en danger l''intérêt général, tout en garantissant leur protection contre d''éventuelles représailles.', 'ALL', 82, 0.42, 0.10, FALSE),
('Protection des données et de la vie privée : déclaration écrite et partagée sur la confidentialité et la protection des informations sensibles des client·es, des travailleur·euses et de l''entreprise, conformément aux lois et réglementations en matière de protection des données.', 'ALL', 82, 0.42, 0.10, FALSE),
('Charte Diversité et Inclusion : déclaration écrite et partagée formalisant l''engagement de votre organisation à promouvoir l''égalité des chances, à valoriser la diversité et à créer un environnement inclusif, respectueux et exempt de discrimination.', 'WORKERS', 82, 0.42, 0.10, FALSE),
('Charte d''engagement civique : déclaration écrite et partagée qui exprime les principes et actions par lesquels une organisation et ses membres s’engagent à contribuer positivement à la société, par le biais d''actions concrètes ou de philantropie.', 'ALL', 82, 0.42, 0.10, FALSE),
('Code de conduite Fournisseurs : déclaration écrite et partagée avec les fournisseurs qui définit les standards éthiques, sociaux et environnementaux que les fournisseurs de votre organisation doivent respecter dans le cadre de leur collaboration.', 'ALL', 82, 0.42, 0.10, FALSE),
('Politique de télétravail : déclaration écrite et partagée pour promouvoir les bonnes pratiques pour gérer l''impact écologique généré par le travail à distance, incluant la consommation d''énergie domestique, l''utilisation des équipements numériques, les déchets électroniques et la réduction des déplacements professionnels.', 'WORKERS', 82, 0.42, 0.10, FALSE),
('Charte d''achat responsable : déclaration écrite et partagée qui formalise les engagements d''une organisation à intégrer des critères éthiques, sociaux et environnementaux dans ses pratiques d''approvisionnement et ses relations avec les fournisseurs.', 'ALL', 82, 0.42, 0.10, FALSE),
('Politique sur le marketing éthique : déclaration écrite et partagée qui établit les principes et pratiques d''une organisation pour promouvoir ses produits ou services de manière transparente, responsable et respectueuse des valeurs sociales, environnementales et des consommateurs.', 'ALL', 82, 0.42, 0.10, FALSE),
('Charte sur les clients des secteurs controversés : déclaration écrite et partagée au sein de l''entreprise, définissant les critères éthiques et responsables qui guident l''acceptation ou le rejet de partenariats avec des entreprises évoluant dans des secteurs jugés socialement, écologiquement ou économiquement problématiques.', 'ALL', 82, 0.42, 0.10, FALSE),
('Aucune des réponses ci-dessus.', 'ALL', 82, 0.0, 0.0, FALSE),
('Une déclaration claire de l''engagement de l''entreprise à prévenir et combattre la corruption sous toutes ses formes.', 'ALL', 83, 1.60, 0.40, FALSE),
('Des lignes directrices sur l''acceptation et l''offre de cadeaux, divertissements et hospitalités, conformément aux normes légales et éthiques.', 'ALL', 83, 1.60, 0.40, FALSE),
('Des formations régulières et des programmes de sensibilisation pour éduquer les employé·es sur les politiques anti-corruption et leurs responsabilités.', 'WORKERS', 83, 1.60, 0.40, FALSE),
('Des mécanismes de signalement et une protection pour les personnes signalant des soupçons de corruption.', 'WORKERS', 83, 1.60, 0.40, FALSE),
('Des procédures de vérification préalable (due diligence) sur les partenaires commerciaux, agents et tiers pour atténuer les risques de corruption.', 'ALL', 83, 1.60, 0.40, FALSE),
('Des contrôles internes et des mécanismes de suivi pour détecter et prévenir les pratiques de corruption.', 'ALL', 83, 2.0, 0.50, FALSE),
('Aucune des réponses ci-dessus.', 'ALL', 83, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 83, 0.0, 0.0, FALSE),
('Plainte pour harcèlement ou discrimination', 'ALL', 84, 0.0, 0.0, FALSE),
('Litige relatif à l''**éthique des affaires**', 'ALL', 84, 0.0, 0.0, FALSE),
('Litige social', 'ALL', 84, 0.0, 0.0, FALSE),
('Grèves', 'ALL', 84, 0.0, 0.0, FALSE),
('Autre : préciser A COMPLETER', 'ALL', 84, 0.0, 0.0, FALSE),
('Non', 'ALL', 84, 0.0, 0.0, FALSE),
('Non', 'ALL', 85, 0.0, 0.0, FALSE),
('Oui : préciser A COMPELTER', 'ALL', 85, 0.0, 0.0, FALSE),

-- 11. PROTECTION  DES DONNEES

('Tous·tes les travailleur·euses ayant accès aux données sont formé·es aux politiques de confidentialité des données (protection des informations sensibles, la prévention des fuites de données et le respect des réglementations en vigueur.', 'WORKERS', 86, 1.14, 0.29, TRUE),
('La désignation d''un.e responsabla à la protection des données (DPO - Data Protection Officer).', 'WORKERS', 86, 1.14, 0.29, FALSE),
('Une politique de cybersécurité clairement définie incluant notamment l''identification des cyber-risques.', 'ALL', 86, 1.14, 0.29, FALSE),
('La réalisation d''audits externes incluant notamment des test de phishing, d''intrusion et de piratage de la sécurité des données.', 'ALL', 86, 2.0, 0.5, FALSE),
('Une couverture d''assurance contre le cyber-risques.', 'ALL', 86, 1.14, 0.29, FALSE),
('Aucune de ces réponses.', 'ALL', 86, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 86, 0.0, 0.0, FALSE),
('Nous avons mis en place quelques mesures de base mais nous ne disposons pas d''une politique de protection de la vie privée formelle.', 'ALL', 87, 1.14, 0.29, FALSE),
('Nous avons formalisé la politique de protection de la vie privée avec une déclaration claire sur notre engagement à protéger la vie privée et la confidentialité des informations personnelles.', 'ALL', 87, 1.14, 0.29, FALSE),
('Nous contrôlons, révisons et mettons à jour continuellement la politique pour faire face aux risques émergents et à l''évolution des exigences réglementaires. ', 'ALL', 87, 1.14, 0.29, FALSE),
('Aucune de ces réponses.', 'ALL', 87, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 87, 0.0, 0.0, FALSE),
('Oui', 'ALL', 88, 0.0, 0.0, TRUE),
('Non', 'ALL', 88, 0.0, 0.0, FALSE),
('Je ne sais pas', 'ALL', 88, 0.0, 0.0, FALSE),

-- 12. CERTIFICATIONS
('0%', 'ALL', 89, 0.0, 0.0, FALSE),
('1-24%', 'ALL', 89, 0.0, 0.0, FALSE),
('25-49%', 'ALL', 89, 0.0, 0.0, FALSE),
('25-49%', 'ALL', 89, 2.0, 0.0, FALSE),
('75-100%', 'ALL', 89, 5.0, 1.25, FALSE),
('75-100%', 'ALL', 89, 0.0, 0.0, FALSE),
('Précisez le nom de l''organisme et/ou label :', 'ALL', 89, 0.0, 0.0, FALSE),
('Non applicable', 'ALL', 89, 0.0, 0.0, FALSE),
('Benefit Corporation (B Corp) ', 'ALL', 90, 5.0, 1.25, FALSE),
('EMAS ou ISO 14001 - Système de management environnemental ', 'ALL', 90, 5.0, 1.25, FALSE),
('ISO 26000 -  Responsabilité sociétale ', 'ALL', 90, 5.0, 1.25, FALSE),
('ISO 9001 - Système de management de qualité ', 'ALL', 90, 5.0, 1.25, FALSE),
('Label Diversité et Inclusion', 'ALL', 90, 5.0, 1.25, FALSE),
('Autre : veuillez préciser dans les commentaires.', 'ALL', 90, 0.0, 0.0, FALSE),
('Non', 'ALL', 90, 0.0, 0.0, FALSE);
