@baseUrl=http://127.0.0.1:3000
@user_token={{ user.response.body.token }}
@admin_token={{ admin.response.body.token }}

### Login with admin account
# @name admin
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
    "login": "admin@example.com",
    "password": "password"
}

### Register with company
POST {{ baseUrl }}/auth/register
Content-Type: application/json
Authorization: Bearer {{ admin_token }}

{
    "firstname": "John",
    "lastname": "Doe",
    "login": "erzvzvz",
    "password": "password",
    "role": "user",
    "company_id": 1
}

### Login with user account
# @name user
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
    "login": "erzvzvz",
    "password": "password"
}

### Add an answer
POST {{ baseUrl }}/answers
Content-Type: application/json

{
    "answer": "cc sava",
    "template": "test",
    "question_id": 1,
    "score": 0.3,
    "engagement_score": 0.5,
    "is_forced_engagement": false,
    "comment": ""

}

### Add an answer for a user
POST {{ baseUrl }}/answers/1
Content-Type: application/json
Authorization: Bearer {{ user_token }}

{
    "form_id": 1,
    "now": true,
    "commitment_pact": false,
    "comment": " "

}

### Get the answers of a question
GET {{ baseUrl }}/answers/1
Authorization: Bearer {{ user_token }}
