@baseUrl=http://127.0.0.1:3000
@user_token={{ user.response.body.token }}
@admin_token={{ admin.response.body.token }}

### Login with admin account
# @name admin
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
    "login": "admin@example.com",
    "password": "password"
}

### Register with company
POST {{ baseUrl }}/auth/register
Content-Type: application/json
Authorization: Bearer {{ admin_token }}

{
    "firstname": "John",
    "lastname": "Doe",
    "login": "erzvzvz",
    "password": "password",
    "role": "user",
    "company_id": 1
}

### Login with user account
# @name user
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
    "login": "user1@example.com",
    "password": "password"
}

### Add an answer
POST {{ baseUrl }}/answers
Content-Type: application/json
Authorization: Bearer {{ admin_token }}

{
    "answer": "cc sava",
    "template": "test",
    "question_id": 1,
    "score": 0.3,
    "engagement_score": 0.5,
    "is_forced_engagement": false,
    "is_forced_comment": false
}

### Add an answer for a user without text
POST {{ baseUrl }}/answers/1
Content-Type: application/json
Authorization: Bearer {{ user_token }}

{
    "form_id": 1,
    "now": true,
    "commitment_pact": false,
    "comment": "Mon commentaire"
}

### Add an answer for a user with text on forced comment
POST {{ baseUrl }}/answers/3
Content-Type: application/json
Authorization: Bearer {{ user_token }}

{
    "form_id": 1,
    "comment": "Mon commentaire"
}

### Add an answer for a user without text on forced comment
POST {{ baseUrl }}/answers/3
Content-Type: application/json
Authorization: Bearer {{ user_token }}

{
    "form_id": 1
}

### Get the answers of a question
GET {{ baseUrl }}/answers/1
Authorization: Bearer {{ user_token }}

### get the score of a form
GET {{ baseUrl }}/score/4
Authorization: Bearer {{ user_token }}

### Validate a user's answer
POST {{ baseUrl }}/answers/1/validate
Content-Type: application/json
Authorization: Bearer {{ admin_token }}

{
    "form_id": 1,
    "now_verif": true,
    "commitment_pact_verif": false,
    "comment": "Mon commentaire"
}

### Validate a non existant user's answer with comment
POST {{ baseUrl }}/answers/1/validate
Content-Type: application/json
Authorization: Bearer {{ admin_token }}

{
    "form_id": 2,
    "comment": "Mon commentaire"
}

### Validate a non existant user's answer without comment
POST {{ baseUrl }}/answers/3/validate
Content-Type: application/json
Authorization: Bearer {{ admin_token }}

{
    "form_id": 2
}

### Update score of an answer ONLY SCORE NOW
PATCH {{ baseUrl }}/answers/1/update-score
Content-Type: application/json
Authorization: Bearer {{ admin_token }}

{
    "score_now": 0.7
}

### Update score of an answer ONLY SCORE ENGAGEMENT
PATCH {{ baseUrl }}/answers/1/update-score
Content-Type: application/json
Authorization: Bearer {{ admin_token }}

{
    "score_commitment_pact": 0.6
}

### Update score of an answer BOTH SCORES
PATCH {{ baseUrl }}/answers/1/update-score
Content-Type: application/json
Authorization: Bearer {{ admin_token }}

{
    "score_now": 2,
    "score_commitment_pact": 0.5
}

### Update score of an answer with wrong value
PATCH {{ baseUrl }}/answers/1/update-score
Content-Type: application/json
Authorization: Bearer {{ admin_token }}

{
    "score_now": -1
}