@baseUrl=http://127.0.0.1:3000

### Register
POST {{ baseUrl }}/auth/register
Content-Type: application/json

{
    "login": "dev",
    "password": "password"
}

### Login with good credentials
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
    "login": "dev",
    "password": "password"
}

> {% client.global.set("token", response.body.token) %}

### Login with bad password
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
    "login": "dev",
    "password": "badpassword"
}

### Login with bad login
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
    "login": "badlogin",
    "password": "password"
}


###
GET {{ baseUrl }}/
Authorization: Bearer {{ token }}