@baseUrl=http://127.0.0.1:3000
@user_token={{ user.response.body.token }}
@admin_token={{ admin.response.body.token }}

### Login with user account
# @name user
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
    "login": "user2@example.com",
    "password": "password"
}

### Login with admin account
# @name admin
POST {{ baseUrl }}/auth/login
Content-Type: application/json

{
    "login": "admin@example.com",
    "password": "password"
}

### Create a form
POST {{ baseUrl }}/forms
Content-Type: application/json
Authorization: Bearer {{ admin_token }}

{
    "company_id": 1,
    "type": "ESG"
}

### Read all forms for a user
GET {{ baseUrl }}/forms/user
Authorization: Bearer {{ user_token }}

### Read all types of forms with their questions & answers, used for managing forms
GET {{ baseUrl }}/forms
Authorization: Bearer {{ admin_token }}

### Submit a form
POST {{ baseUrl }}/forms/2/submit
Content-Type: application/json
Authorization: Bearer {{ user_token }}

{
    "confirmation": true
}

### Validate a form
POST {{ baseUrl }}/forms/3/validate
Authorization: Bearer {{ admin_token }}