@baseUrl=http://127.0.0.1:3000

### Add a question
POST {{ baseUrl }}/questions
Content-Type: application/json

{
    "question_status": "A compléter",
    "category": "TEST",
    "sub_category": "TEST",
    "question": "cc sava"
}

### Add a question with empty question
POST {{ baseUrl }}/questions
Content-Type: application/json

{
    "question_status": "A compléter",
    "category": "TEST",
    "sub_category": "TEST",
    "question": ""
}

### Get one question
GET {{ baseUrl }}/questions/1

### Get a question that does not exist
GET {{ baseUrl }}/questions/100