@baseUrl=http://127.0.0.1:3000

### Add a question
POST {{ baseUrl }}/questions
Content-Type: application/json

{
    "category": "TEST",
    "sub_category": "TEST",
    "question": "cc sava"
}

### Add a question with empty question
POST {{ baseUrl }}/questions
Content-Type: application/json

{
    "category": "TEST",
    "sub_category": "TEST",
    "question": ""
}

### Get one question
GET {{ baseUrl }}/questions/1

### Get a question that does not exist
GET {{ baseUrl }}/questions/100

### Update a question
PUT {{ baseUrl }}/questions/1
Content-Type: application/json

{
    "question": "cc sava je modifie hihihi"
}

### Update a question with empty question
PUT {{ baseUrl }}/questions/1
Content-Type: application/json

{
    "question": ""
}

### Delete a question
PUT {{ baseUrl }}/questions/1
Content-Type: application/json

{
    "is_used": false
}